/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import services.KhuyenMaiServices;
import services.SanPhamServices;
import viewmodel.BoPhanThitViewModel;
import viewmodel.DonViTinhViewModel;
import viewmodel.GiaSucViewModel;
import viewmodel.GiamGiaTheoHSDViewModel;
import viewmodel.LoaiThitViewModel;

/**
 *
 * @author Toan
 */
public class SanPhamView extends javax.swing.JPanel {

    /**
     * Creates new form SanPhamThit
     */
    private final KhuyenMaiServices khuyenMaiServ;
    private final SanPhamServices sanPhamServ;
    private ArrayList<LoaiThitViewModel> listLoaiThit;
    private DefaultComboBoxModel<String> dcbm;
    DefaultTableModel dtm;
    public SanPhamView() {
        initComponents();
        sanPhamServ = new SanPhamServices();
        khuyenMaiServ = new KhuyenMaiServices();
        loadTable();
        loadTableKM();
        loadCBBGiaSuc();
        loadCBBBoPhan();
        loadCBBDonViTinh();
        clearForm();
        
    }
    public void loadTableKM(){
        dtm = (DefaultTableModel) tblKhuyenMai.getModel();
        dtm.setRowCount(0);
        for(GiamGiaTheoHSDViewModel x:khuyenMaiServ.getAll()){
            Object[] rowData = {
                x.getHsdConLai(),
                x.getGiamGia()
            };
            dtm.addRow(rowData);
        }
    }
    public void loadCBBGiaSuc (){
        dcbm = (DefaultComboBoxModel<String>) cbbGiaSuc.getModel();
        dcbm.removeAllElements();
        for(GiaSucViewModel x:sanPhamServ.getAllGiaSuc()){
            dcbm.addElement(x.getTenGiaSuc());
        }
    }
    public void loadCBBBoPhan(){
        dcbm = (DefaultComboBoxModel<String>) cbbBoPhan.getModel();
        dcbm.removeAllElements();
        for(BoPhanThitViewModel x:sanPhamServ.getAllBoPhan()){
            dcbm.addElement(x.getTen());
        }
    }    
    public void loadCBBDonViTinh(){
        dcbm = (DefaultComboBoxModel<String>) cbbDonViTinh.getModel();
        dcbm.removeAllElements();
        for(DonViTinhViewModel x:sanPhamServ.getAllDonViTinh()){
            dcbm.addElement(x.getTenDonVi());
        }
    }
    public void clearForm(){
        lbID.setText("txtID");
        txtMa.setText("");
        txtGiaTien.setText("");
        cbbBoPhan.setSelectedIndex(0);
        cbbDonViTinh.setSelectedIndex(0);
        cbbGiaSuc.setSelectedIndex(0);
    }
    public void loadTable() {
        dtm = (DefaultTableModel) tblLoaiThit.getModel();
        dtm.setRowCount(0);
        listLoaiThit = sanPhamServ.getAllLoaiThit();
        for (LoaiThitViewModel x : listLoaiThit) {
            Object[] rowData = {
                x.getMaLoaiThit(),
                x.getTenBoPhan() + " " + x.getTenGiaSuc(),
                x.getGiaTien(),
                x.getTenDonViTinh()
            };
            dtm.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbbGiaSuc = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbbBoPhan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbbDonViTinh = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtGiaTien = new javax.swing.JTextField();
        btnAddGiaSuc = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnAddBoPhan = new javax.swing.JButton();
        btnAddDonVi = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiThit = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtPhanTramGiam = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblIDKM = new javax.swing.JLabel();
        btnThemKM = new javax.swing.JButton();
        btnSuaKM = new javax.swing.JButton();
        btnXoaKM = new javax.swing.JButton();
        btnMoiKM = new javax.swing.JButton();
        txtHSDConLai = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("ID:");

        lbID.setText("123456789");

        jLabel3.setText("Mã loại thịt:");

        jLabel4.setText("Tên gia súc:");

        cbbGiaSuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Tên bộ phận thịt:");

        cbbBoPhan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Đơn vị tính:");

        cbbDonViTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Giá tiền / đơn vị tính");

        btnAddGiaSuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnAddGiaSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGiaSucActionPerformed(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Text.png"))); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnAddBoPhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnAddBoPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBoPhanActionPerformed(evt);
            }
        });

        btnAddDonVi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnAddDonVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDonViActionPerformed(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbGiaSuc, 0, 181, Short.MAX_VALUE)
                            .addComponent(cbbBoPhan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddGiaSuc)
                            .addComponent(btnAddBoPhan)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMoi))
                            .addComponent(btnTimKiem))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbbDonViTinh, 0, 164, Short.MAX_VALUE)
                            .addComponent(txtGiaTien))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddDonVi)
                        .addGap(38, 38, 38))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(lbID)
                                .addComponent(jLabel7))
                            .addComponent(cbbDonViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnAddDonVi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddBoPhan)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(cbbGiaSuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddGiaSuc)
                            .addComponent(btnTimKiem))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cbbBoPhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAdd)
                                .addComponent(btnSua)
                                .addComponent(btnXoa)
                                .addComponent(btnMoi)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tblLoaiThit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã", "Tên loại thịt", "Giá tiền/1 đơn vị", "Đơn vị"
            }
        ));
        tblLoaiThit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiThitMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiThit);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý sản phẩm thịt tươi", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Phần trăm giảm giá");

        jLabel11.setText("Phầm trăm hạn sử dụng còn lại");

        jLabel13.setText("ID:");

        lblIDKM.setText("12312321");

        btnThemKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add.png"))); // NOI18N
        btnThemKM.setText("Thêm");
        btnThemKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKMActionPerformed(evt);
            }
        });

        btnSuaKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Edit.png"))); // NOI18N
        btnSuaKM.setText("Sửa");
        btnSuaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaKMActionPerformed(evt);
            }
        });

        btnXoaKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btnXoaKM.setText("Xóa");
        btnXoaKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKMActionPerformed(evt);
            }
        });

        btnMoiKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Text.png"))); // NOI18N
        btnMoiKM.setText("Mới");
        btnMoiKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiKMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHSDConLai, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(txtPhanTramGiam)
                            .addComponent(lblIDKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnThemKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuaKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoiKM)
                        .addGap(0, 63, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(txtPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblIDKM))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtHSDConLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemKM)
                    .addComponent(btnSuaKM)
                    .addComponent(btnXoaKM)
                    .addComponent(btnMoiKM))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "% HSD còn lại", "% Giảm giá"
            }
        ));
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKhuyenMai);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý giảm giá theo hạn sử dụng", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        LoaiThitViewModel loaiThitVM = new LoaiThitViewModel();
        loaiThitVM.setTenBoPhan(cbbBoPhan.getSelectedItem().toString());
        loaiThitVM.setTenGiaSuc(cbbGiaSuc.getSelectedItem().toString());

        listLoaiThit = sanPhamServ.selectPromotedLoaiThit(loaiThitVM);
        if (!listLoaiThit.get(0).getTenBoPhan().equals(loaiThitVM.getTenBoPhan())
                || !listLoaiThit.get(0).getTenGiaSuc().equals(loaiThitVM.getTenGiaSuc())) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy loại thịt này");
            return;
        }
        DefaultTableModel dtm = (DefaultTableModel) tblLoaiThit.getModel();
        dtm.setRowCount(0);
        for (LoaiThitViewModel x : sanPhamServ.selectPromotedLoaiThit(loaiThitVM)) {
            Object[] rowData = {
                x.getMaLoaiThit(),
                x.getTenBoPhan() + " " + x.getTenGiaSuc(),
                x.getGiaTien(),
                x.getTenDonViTinh()
            };
            dtm.addRow(rowData);
        }
        showDataToForm(0);
    }//GEN-LAST:event_btnTimKiemActionPerformed
    public void showDataToForm(int row){
        LoaiThitViewModel loaiThit = listLoaiThit.get(row);
        lbID.setText(loaiThit.getId());
        cbbBoPhan.setSelectedItem(loaiThit.getTenBoPhan());
        cbbGiaSuc.setSelectedItem(loaiThit.getTenGiaSuc());
        cbbDonViTinh.setSelectedItem(loaiThit.getTenDonViTinh());
        txtMa.setText(loaiThit.getMaLoaiThit());
        txtGiaTien.setText(loaiThit.getGiaTien());
    }
    private void tblLoaiThitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiThitMouseClicked
        int row = tblLoaiThit.getSelectedRow();
        if(row == -1)return;
        showDataToForm(row);
    }//GEN-LAST:event_tblLoaiThitMouseClicked

    private void btnAddGiaSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGiaSucActionPerformed
        String maGiaSuc = JOptionPane.showInputDialog(this, "Nhập mã gia súc:");
        String tenGiaSuc = JOptionPane.showInputDialog(this, "Nhập tên gia súc:");
        GiaSucViewModel newGiaSuc = new GiaSucViewModel(null, maGiaSuc, tenGiaSuc);
        String noti = sanPhamServ.addGiaSuc(newGiaSuc);
        JOptionPane.showMessageDialog(this, noti);
        loadCBBGiaSuc();
    }//GEN-LAST:event_btnAddGiaSucActionPerformed

    private void btnAddBoPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBoPhanActionPerformed
        String maBoPhan = JOptionPane.showInputDialog(this, "Nhập mã bộ phận:");
        String tenBoPhan = JOptionPane.showInputDialog(this, "Nhập tên bộ phận:");
        BoPhanThitViewModel newBoPhan = new BoPhanThitViewModel(null, maBoPhan, tenBoPhan);
        String noti = sanPhamServ.addBoPhanThit(newBoPhan);
        JOptionPane.showMessageDialog(this, noti);
        loadCBBBoPhan();
    }//GEN-LAST:event_btnAddBoPhanActionPerformed

    private void btnAddDonViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDonViActionPerformed
        String tenDonVi = JOptionPane.showInputDialog(this, "Nhập tên đơn vị:");
        String quyDoi = JOptionPane.showInputDialog(this, "Nhập số lượng quy đổi ra gram:");
        DonViTinhViewModel donViTinh = new DonViTinhViewModel(null, tenDonVi, quyDoi);
        String noti = sanPhamServ.addDonViTinh(donViTinh);
        JOptionPane.showMessageDialog(this, noti);
        loadCBBDonViTinh();
    }//GEN-LAST:event_btnAddDonViActionPerformed

    public LoaiThitViewModel getDataFromForm(){
        LoaiThitViewModel loaiThit = new LoaiThitViewModel();
        loaiThit.setId(lbID.getText());
        loaiThit.setMaLoaiThit(txtMa.getText());
        loaiThit.setTenBoPhan(cbbBoPhan.getSelectedItem().toString());
        loaiThit.setTenDonViTinh(cbbDonViTinh.getSelectedItem().toString());
        loaiThit.setTenGiaSuc(cbbGiaSuc.getSelectedItem().toString());
        loaiThit.setGiaTien(txtGiaTien.getText());
        return loaiThit;
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String noti = sanPhamServ.addLoaiThit(getDataFromForm());
        JOptionPane.showMessageDialog(this, noti);
        if(!noti.contains("thành công")){
            return;
        }
        loadTable();
        clearForm();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tblLoaiThit.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa");
            return;
        }
        if(JOptionPane.YES_OPTION != JOptionPane.showConfirmDialog(this, "Bạn chắc chắn sửa không?")){
            return;
        }
        String noti = sanPhamServ.updateLoaiThit(getDataFromForm());
        JOptionPane.showMessageDialog(this, noti);
        if(!noti.contains("thành công")){
            return;
        }
        loadTable();
        clearForm();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblLoaiThit.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa");            
            return;
        }
        if(JOptionPane.YES_OPTION != JOptionPane.showConfirmDialog(this, "Bạn chắc chắn xóa không?")){
            return;
        }
        
        String noti = sanPhamServ.deleteLoaiThit(lbID.getText());
        JOptionPane.showMessageDialog(this, noti);
        if(!noti.contains("thành công")){
            return;
        }
        loadTable();
        clearForm();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenMaiMouseClicked
        int row = tblKhuyenMai.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để thao tác");            
            return;
        }
        GiamGiaTheoHSDViewModel giamGia = khuyenMaiServ.getAll().get(row);
        lbID.setText(giamGia.getId());
        txtHSDConLai.setText(giamGia.getHsdConLai());
        txtPhanTramGiam.setText(giamGia.getGiamGia());
    }//GEN-LAST:event_tblKhuyenMaiMouseClicked
    private void clearFormKM(){
        lblIDKM.setText("txtID");
        txtHSDConLai.setText("");
        txtPhanTramGiam.setText("");
    }
    private void btnMoiKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiKMActionPerformed
        clearFormKM();
    }//GEN-LAST:event_btnMoiKMActionPerformed

    private void btnThemKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKMActionPerformed
        String noti = khuyenMaiServ.add(
                new GiamGiaTheoHSDViewModel(
                        lblIDKM.getText(),
                        txtHSDConLai.getText(),
                        txtPhanTramGiam.getText()));
        JOptionPane.showMessageDialog(this, noti);
        if(!noti.contains("thành công")){
            return;
        }
        loadTableKM();
        clearFormKM();
    }//GEN-LAST:event_btnThemKMActionPerformed

    private void btnSuaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaKMActionPerformed
        int row = tblKhuyenMai.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần thao tác");            
            return;
        }
        if(JOptionPane.YES_OPTION != JOptionPane.showConfirmDialog(this, "Bạn chắc chắn sửa không?")){
            return;
        }
        String noti = khuyenMaiServ.update(
                new GiamGiaTheoHSDViewModel(
                        lblIDKM.getText(),
                        txtHSDConLai.getText(),
                        txtPhanTramGiam.getText()));
        JOptionPane.showMessageDialog(this, noti);
        if(!noti.contains("thành công")){
            return;
        }
        loadTableKM();
        clearFormKM();
    }//GEN-LAST:event_btnSuaKMActionPerformed

    private void btnXoaKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKMActionPerformed
        int row = tblKhuyenMai.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần thao tác");            
            return;
        }
        if(JOptionPane.YES_OPTION != JOptionPane.showConfirmDialog(this, "Bạn chắc chắn sửa không?")){
            return;
        }
        String noti = khuyenMaiServ.delete(lblIDKM.getText());
        JOptionPane.showMessageDialog(this, noti);
        if(!noti.contains("thành công")){
            return;
        }
        loadTableKM();
        clearFormKM();
    }//GEN-LAST:event_btnXoaKMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddBoPhan;
    private javax.swing.JButton btnAddDonVi;
    private javax.swing.JButton btnAddGiaSuc;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnMoiKM;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaKM;
    private javax.swing.JButton btnThemKM;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaKM;
    private javax.swing.JComboBox<String> cbbBoPhan;
    private javax.swing.JComboBox<String> cbbDonViTinh;
    private javax.swing.JComboBox<String> cbbGiaSuc;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lblIDKM;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTable tblLoaiThit;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtHSDConLai;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtPhanTramGiam;
    // End of variables declaration//GEN-END:variables
}
