/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import services.TrangChuServices;
import thread.Clock;

/**
 *
 * @author Toan
 */
public class TrangChuNhanvienView extends javax.swing.JFrame {

    private SanPhamView spThit;
    private NhanVienView nv;
    private KhachHangView kh;
    private GioHangView gh;
    private HoaDonView hd;
    private DoanhThuView dt;
    private String idNV;
    private final TrangChuServices trangChuServ;
    /**
     * Creates new form TrangChuView
     */
    public TrangChuNhanvienView(String idNV) {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(false);
        this.idNV = idNV;
        trangChuServ = new TrangChuServices();
        txtNhanVien.setText("Nhân viên:"+trangChuServ.getTenNhanVien(idNV));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        panel_SanPham = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel_KhachHang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panel_GioHang = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panel_NhanVien = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        panel_ThanhToan = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        panel_DoanhThu = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtDate = new javax.swing.JLabel();
        txtClock = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JLabel();
        tabpQL = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        backGround.setBackground(new java.awt.Color(255, 255, 255));
        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(54, 33, 89));
        sidepane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidepaneMouseDragged(evt);
            }
        });
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_SanPham.setBackground(new java.awt.Color(85, 65, 118));
        panel_SanPham.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                panel_SanPhamAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        panel_SanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_SanPhamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_SanPhamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_SanPhamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_SanPhamMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/meat.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Sản Phẩm");

        javax.swing.GroupLayout panel_SanPhamLayout = new javax.swing.GroupLayout(panel_SanPham);
        panel_SanPham.setLayout(panel_SanPhamLayout);
        panel_SanPhamLayout.setHorizontalGroup(
            panel_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        panel_SanPhamLayout.setVerticalGroup(
            panel_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_SanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_SanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(panel_SanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 50));

        panel_KhachHang.setBackground(new java.awt.Color(85, 65, 118));
        panel_KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_KhachHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_KhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_KhachHangMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rating.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Khách Hàng");

        javax.swing.GroupLayout panel_KhachHangLayout = new javax.swing.GroupLayout(panel_KhachHang);
        panel_KhachHang.setLayout(panel_KhachHangLayout);
        panel_KhachHangLayout.setHorizontalGroup(
            panel_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_KhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        panel_KhachHangLayout.setVerticalGroup(
            panel_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_KhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(panel_KhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 230, -1));

        panel_GioHang.setBackground(new java.awt.Color(85, 65, 118));
        panel_GioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_GioHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_GioHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_GioHangMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-cart.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Giỏ Hàng");

        javax.swing.GroupLayout panel_GioHangLayout = new javax.swing.GroupLayout(panel_GioHang);
        panel_GioHang.setLayout(panel_GioHangLayout);
        panel_GioHangLayout.setHorizontalGroup(
            panel_GioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_GioHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        panel_GioHangLayout.setVerticalGroup(
            panel_GioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_GioHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_GioHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(panel_GioHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cửa hàng");
        sidepane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 20));

        panel_NhanVien.setBackground(new java.awt.Color(85, 65, 118));
        panel_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_NhanVienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_NhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_NhanVienMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/management.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Nhân Viên");

        javax.swing.GroupLayout panel_NhanVienLayout = new javax.swing.GroupLayout(panel_NhanVien);
        panel_NhanVien.setLayout(panel_NhanVienLayout);
        panel_NhanVienLayout.setHorizontalGroup(
            panel_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_NhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        panel_NhanVienLayout.setVerticalGroup(
            panel_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_NhanVienLayout.createSequentialGroup()
                .addGroup(panel_NhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_NhanVienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_NhanVienLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(panel_NhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 230, -1));

        panel_ThanhToan.setBackground(new java.awt.Color(85, 65, 118));
        panel_ThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_ThanhToanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_ThanhToanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_ThanhToanMouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png"))); // NOI18N

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Hóa Đơn");

        javax.swing.GroupLayout panel_ThanhToanLayout = new javax.swing.GroupLayout(panel_ThanhToan);
        panel_ThanhToan.setLayout(panel_ThanhToanLayout);
        panel_ThanhToanLayout.setHorizontalGroup(
            panel_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        panel_ThanhToanLayout.setVerticalGroup(
            panel_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(panel_ThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 230, -1));

        panel_DoanhThu.setBackground(new java.awt.Color(85, 65, 118));
        panel_DoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_DoanhThuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_DoanhThuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_DoanhThuMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/economy.png"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Doanh thu");

        javax.swing.GroupLayout panel_DoanhThuLayout = new javax.swing.GroupLayout(panel_DoanhThu);
        panel_DoanhThu.setLayout(panel_DoanhThuLayout);
        panel_DoanhThuLayout.setHorizontalGroup(
            panel_DoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel15)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        panel_DoanhThuLayout.setVerticalGroup(
            panel_DoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_DoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidepane.add(panel_DoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 230, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Thịt tươi");
        sidepane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        backGround.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 750));

        jPanel3.setBackground(new java.awt.Color(122, 72, 221));

        txtDate.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtDate.setForeground(new java.awt.Color(204, 204, 204));
        txtDate.setText("dd-MM-yyyy");

        txtClock.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtClock.setForeground(new java.awt.Color(204, 204, 204));
        txtClock.setText("00:00 am");

        txtNhanVien.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        txtNhanVien.setForeground(new java.awt.Color(204, 204, 204));
        txtNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 710, Short.MAX_VALUE)
                        .addComponent(txtNhanVien))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtClock)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(txtClock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate)
                    .addComponent(txtNhanVien))
                .addGap(17, 17, 17))
        );

        backGround.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 980, 100));
        backGround.add(tabpQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 980, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, 1211, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sidepaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepaneMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_sidepaneMouseDragged

    private void panel_SanPhamAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_panel_SanPhamAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_SanPhamAncestorAdded

    private void panel_SanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_SanPhamMouseClicked
        // TODO add your handling code here:
//        if (spThit == null) {
//            try {
//                spThit = new SanPhamView();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//
//        }
//        tabpQL.addTab("Quản lý sản phẩm", spThit);
//        tabpQL.remove(nv);
//        tabpQL.remove(kh);
//        tabpQL.remove(gh);
//        tabpQL.remove(hd);
//        tabpQL.remove(dt);
        JOptionPane.showMessageDialog(this, "Nhân viên không được truy cập vào mục này !");
    }//GEN-LAST:event_panel_SanPhamMouseClicked

    private void panel_KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_KhachHangMouseClicked
//        if (kh == null) {
//            try {
//                kh = new KhachHangView();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
//        tabpQL.addTab("Quản lý khách Hàng", kh);
//        tabpQL.remove(nv);
//        tabpQL.remove(spThit);
//        tabpQL.remove(gh);
//        tabpQL.remove(hd);
//        tabpQL.remove(dt);
        JOptionPane.showMessageDialog(this, "Nhân viên không được truy cập vào mục này !");
    }//GEN-LAST:event_panel_KhachHangMouseClicked

    private void panel_SanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_SanPhamMousePressed
        // TODO add your handling code here:
//        if(evt.getClickCount()>=2){
//            tabpQL.
//        }
    }//GEN-LAST:event_panel_SanPhamMousePressed

    private void panel_GioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_GioHangMouseClicked
        // TODO add your handling code here:
        if (gh == null) {
            try {
                gh = new GioHangView(idNV);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        tabpQL.addTab("Quản lý giỏ hàng", gh);
        tabpQL.setSelectedComponent(gh);
        tabpQL.remove(spThit);
        tabpQL.remove(kh);
        tabpQL.remove(nv);
        tabpQL.remove(hd);
        tabpQL.remove(dt);
    }//GEN-LAST:event_panel_GioHangMouseClicked

    private void panel_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_NhanVienMouseClicked
        // TODO add your handling code here:
//        if (nv == null) {
//            try {
//                nv = new NhanVienView();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
//        tabpQL.addTab("Quản lý nhân viên", nv);
//        tabpQL.remove(spThit);
//        tabpQL.remove(kh);
//        tabpQL.remove(gh);
//        tabpQL.remove(hd);
//        tabpQL.remove(dt);
        JOptionPane.showMessageDialog(this, "Nhân viên không được truy cập vào mục này !");
    }//GEN-LAST:event_panel_NhanVienMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        gh = new GioHangView(idNV);
        tabpQL.addTab("Quản lý giỏ hàng", gh);
        Clock thread = new Clock(txtClock);
        Thread t1 = new Thread(thread);
        t1.start();
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        txtDate.setText(sdf.format(date));
    }//GEN-LAST:event_formWindowOpened

    private void panel_SanPhamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_SanPhamMouseEntered
        // TODO add your handling code here:
        panel_SanPham.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_panel_SanPhamMouseEntered

    private void panel_SanPhamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_SanPhamMouseExited
        // TODO add your handling code here:
        panel_SanPham.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_panel_SanPhamMouseExited

    private void panel_ThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ThanhToanMouseClicked
        // TODO add your handling code here:
//        if (hd == null) {
//            try {
//                hd = new HoaDonView();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//
//        }
//        tabpQL.addTab("Hóa đơn", hd);
//        tabpQL.remove(spThit);
//        tabpQL.remove(kh);
//        tabpQL.remove(gh);
//        tabpQL.remove(nv);
//        tabpQL.remove(dt);
        JOptionPane.showMessageDialog(this, "Nhân viên không được truy cập vào mục này !");
    }//GEN-LAST:event_panel_ThanhToanMouseClicked

    private void panel_KhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_KhachHangMouseEntered
        // TODO add your handling code here:

        panel_KhachHang.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_panel_KhachHangMouseEntered

    private void panel_KhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_KhachHangMouseExited
        // TODO add your handling code here:
        panel_KhachHang.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_panel_KhachHangMouseExited

    private void panel_NhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_NhanVienMouseEntered
        // TODO add your handling code here:
        panel_NhanVien.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_panel_NhanVienMouseEntered

    private void panel_NhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_NhanVienMouseExited
        // TODO add your handling code here:
        panel_NhanVien.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_panel_NhanVienMouseExited

    private void panel_GioHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_GioHangMouseEntered
        // TODO add your handling code here:
        panel_GioHang.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_panel_GioHangMouseEntered

    private void panel_GioHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_GioHangMouseExited
        // TODO add your handling code here:
        panel_GioHang.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_panel_GioHangMouseExited

    private void panel_ThanhToanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ThanhToanMouseEntered
        // TODO add your handling code here:
        panel_ThanhToan.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_panel_ThanhToanMouseEntered

    private void panel_ThanhToanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ThanhToanMouseExited
        // TODO add your handling code here:
        panel_ThanhToan.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_panel_ThanhToanMouseExited

    private void panel_DoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_DoanhThuMouseClicked
        // TODO add your handling code here:
//        if(dt==null){
//            dt = new DoanhThuView();
//        }
//        tabpQL.addTab("Doanh thu", dt);
//        tabpQL.remove(nv);
//        tabpQL.remove(kh);
//        tabpQL.remove(gh);
//        tabpQL.remove(hd);
//        tabpQL.remove(spThit );
        JOptionPane.showMessageDialog(this, "Nhân viên không được truy cập vào mục này !");
    }//GEN-LAST:event_panel_DoanhThuMouseClicked

    private void panel_DoanhThuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_DoanhThuMouseEntered
        // TODO add your handling code here:
        panel_DoanhThu.setBackground(new Color(122, 72, 221));
    }//GEN-LAST:event_panel_DoanhThuMouseEntered

    private void panel_DoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_DoanhThuMouseExited
        // TODO add your handling code here:
        panel_DoanhThu.setBackground(new Color(85, 65, 118));
    }//GEN-LAST:event_panel_DoanhThuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuNhanvienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuNhanvienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuNhanvienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuNhanvienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuNhanvienView(null).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backGround;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel_DoanhThu;
    private javax.swing.JPanel panel_GioHang;
    private javax.swing.JPanel panel_KhachHang;
    private javax.swing.JPanel panel_NhanVien;
    private javax.swing.JPanel panel_SanPham;
    private javax.swing.JPanel panel_ThanhToan;
    private javax.swing.JPanel sidepane;
    private javax.swing.JTabbedPane tabpQL;
    private javax.swing.JLabel txtClock;
    private javax.swing.JLabel txtDate;
    private javax.swing.JLabel txtNhanVien;
    // End of variables declaration//GEN-END:variables
}
